config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  root 'categories#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resources :fishings, only: [:new, :create, :destroy, :edit, :update]
  resources :votes, only: [:new, :create, :destroy]
  resources :categories, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorize.rb
class Categorize < ApplicationRecord
  belongs_to :category
  belongs_to :fishing
  validates :category_id, presence: true
  validates :fishing_id, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizes, dependent: :delete_all
  has_many :fishings, through: :categorizes, dependent: :delete_all

  validates :name, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :priority, presence: true

  scope :order_by_priority, -> { order(:priority) }
end

app/models/fishing.rb
class Fishing < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :votes, dependent: :delete_all
  has_many :categorizes, dependent: :delete_all
  has_many :categories, through: :categorizes, dependent: :delete_all

  has_one_attached :image

  validates :title, presence: true, uniqueness: true, length: { in: 5..50 }
  validates :text, presence: true, length: { in: 5..200 }

  scope :order_by_votes, -> { order(votes_count: :desc) }
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { in: 3..15 }

  has_many :fishings, foreign_key: :author_id, dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :fishing, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :user_sign_in?
  helper_method :authenticate_user

  def current_user
    User.find_by(id: session[:user_id])
  end

  def user_sign_in?
    !current_user.nil?
  end

  def authenticate_user
    redirect_to login_path if current_user.nil?
  end
end

app/controllers/categories_controller.rb
# rubocop:disable Layout/LineLength
class CategoriesController < ApplicationController
  def index
    @more_important_categories = Category.all.order_by_priority
    @favorite_fishings = Fishing.all.order_by_votes.first
  end

  def show
    @category = Category.find(params[:id])
    @fishings_by_category = Fishing.includes(:author).includes(:categories).where(categories: { id: params[:id] }).order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

# rubocop:enable Layout/LineLength

app/controllers/fishings_controller.rb
class FishingsController < ApplicationController
  before_action :authenticate_user, only: %i[new create]
  before_action :check_categories, only: %i[create update]

  def index; end

  def new
    @fishing = Fishing.new
  end

  def create
    @fishing = current_user.fishings.build(fishing_params)

    if @fishing.save
      @cat_ids_arr = fishing_params[:category_id][1..]
      @cat_ids_arr.map!(&:to_i)
      @category = Category.where(id: @cat_ids_arr)
      @fishing.categories << @category
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    @fishing = Fishing.find(params[:id])
    @fishing.destroy
    redirect_to root_path
  end

  def edit
    @fishing = Fishing.find(params[:id])
  end

  def update
    @fishing = Fishing.find(params[:id])
    @fishing.categories.delete_all
    @cat_ids_arr = fishing_params[:category_id][1..]
    @cat_ids_arr.map!(&:to_i)
    @category = Category.where(id: @cat_ids_arr)
    @fishing.categories << @category

    @fishing.update_attributes(fishing_params)
    redirect_to root_path
  end

  def check_categories
    @fishing = Fishing.new
    return unless fishing_params[:category_id][0].blank? && fishing_params[:category_id][1].blank?

    @fishing.errors.add(:category_id, "can't be blank")
    render 'new'
  end

  private

  def fishing_params
    params.require(:fishing).permit(:author_id, :title, :text, :image, category_id: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_name(params[:name])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @vote = Vote.new
  end

  def create
    @category = Category.find_by_id(params[:id])
    @vote = current_user.votes.build(fishing_id: params[:fishing_id])
    @vote.save
    redirect_to @category
  end

  def destroy
    @vote = current_user.votes.find_by(fishing_id: params[:fishing_id])
    @vote.destroy
    redirect_to category_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def first_article_by_category(c_id)
    @first_article = if Categorize.where(category_id: c_id).present? == false
                       'n/a'
                     else
                       Fishing.includes(:categories).where(categories: { id: c_id }).order(created_at: :desc).first
                     end
  end

  def check_img_exist(art)
    @img = if art.image.present?
             art.image
           elsif art.imagen.present?
             art.imagen
           else
             'default_img.jpg'
           end
  end

  def edit_article(article)
    return unless user_sign_in? && (current_user.id == article.author_id)

    link_to 'Edit', edit_fishing_path(article), class: 'text-decoration-none fw-bold'
  end

  def delete_article(article)
    return unless user_sign_in? && (current_user.id == article.author_id)

    link_to 'Delete', fishing_path(article), method: :delete, class: 'text-decoration-none fw-bold'
  end
end

app/helpers/fishings_helper.rb
module FishingsHelper
  def fishing_errors
    return unless @fishing.errors.any?

    @fishing.errors.full_messages.each do |msg|
      if msg.include?('Title')
        @fclass1 = 'border border-danger'
      elsif msg.include?('Text')
        @fclass2 = 'border border-danger'
      end
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def nav_bar_buttons
    if user_sign_in?
      @article = link_to 'ARTICLE', new_fishing_path, class: 'text-decoration-none'
      @so_button = link_to 'LOGOUT', logout_path, class: 'text-decoration-none'
      @welcome = "Welcome #{current_user.name}!"
    else
      @su_button = link_to 'REGISTER', new_user_path, class: 'text-decoration-none'
      @si_button = link_to 'LOGIN', login_path, class: 'text-decoration-none'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_errors
    return unless @user.errors.any?

    @user.errors.full_messages.each do |msg|
      @uclas1 = 'border border-danger' if msg.include?('Name')
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_unvote(f_id, c_id)
    return unless user_sign_in?

    if current_user.votes.find_by(fishing_id: f_id)
      link_to 'Unvote', vote_path(fishing_id: f_id), method: :delete, class: 'text-decoration-none fw-bold'
    else
      link_to 'Vote', votes_path(fishing_id: f_id, id: c_id), method: :post, class: 'text-decoration-none fw-bold'
    end
  end
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.number_field :priority %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<br>
<br>
  <div class="row g-0">
    <div class="col-9">
      <div class="card">
        <%check_img_exist(@favorite_fishings)%>
        <div class="main_article_img_container">
          <%= image_tag( @img, alt: "default_image", class: "card-img main_article_img") %>
        </div>
        <div class="card-img-overlay d-flex flex-column">
          <div class="mt-auto">
          <h4 class="card-title fw-bold"><%=@favorite_fishings.title%></h4>
          <p class="card-text text-white fw-bold"><%= @favorite_fishings.text %></p>
        </div>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="wheather_img_container">
        <%= image_tag( "weather_img.webp", alt: "default_image", class: "wheather_img") %>
      </div>
    </div>
  </div>
  

  <div class="row g-0">
      <% @more_important_categories.each do |c| %>
      <div class="col-3">
        <div class="card">
          <%first_article_by_category(c.id)%>
          <%check_img_exist(@first_article)%> 
          <div class="category_imgs_container">
            <%= image_tag( @img, alt: "default_image", class: "category_imgs card-img ") %>
          </div>
          <div class="card-img-overlay d-flex flex-column">
            <h4 class="card-title" id="categoryLink"><%=link_to c.name, category_path(c), class: "text-decoration-none text-dark fw-bold"%></h4>
            <h6 class="card-text mt-auto text-white fw-bold"><%=@first_article.title%></h6>
          </div>
        </div>
      </div>
      <% end %>
  </div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="">
  <div class="row g-0 show_cat_container centered">
    <%@fishings_by_category.each do |a|%>
      <div class="col-6">
        <div class="card" >
          <div class="row g-0">
            <div class="col-md-6">
              <%check_img_exist(a)%>
              <%= image_tag( @img, alt: "default_image", class: "card-img-top") %> 
            </div>
            <div class="col-6 p-2 d-flex flex-column justify-content-between">
              <h5 class="category_titles_2"><%=@category.name%></h5>
              <div>
                <h5><%=a.title%></h5>
                <p><%= a.text %></p>
                <p class="text-secondary"><%="By #{a.author.name}" %></p>
              </div>
              
              <div class="d-flex justify-content-between">
                <span><%="Votes:#{a.votes.count}"%></span>
                <span id="voteLink"><%= vote_unvote(a.id, @category.id)%></span>
                <%= edit_article(a)%>
                <%= delete_article(a)%>
              </div>
            </div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/fishings/_form.html.erb
<%= form_with(model: fishing, local: true) do |form| %>
  <% if fishing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fishing.errors.count, "error") %> prohibited this fishing from being saved:</h2>

      <ul>
        <% fishing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.number_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :imagen %>
    <%= form.text_field :imagen %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fishings/edit.html.erb
<div class="w-50 border border-secondary p-3 rounded centered_XY">
  <h5 class="text-center titles_color">Edit Article</h5>
  <%= form_for @fishing, url: {action: "update"} do |f| %>
      <%= f.text_field :title, placeholder: "Title", class:"form-control my-2 #{@clas1}" %>
      <%= f.text_field :text, placeholder: "Content", class:"form-control my-2 #{@clas2}" %>
      <%= f.file_field :image, class:'form-control my-2' %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: 'Select a Category'}, { multiple: true, class: "btn btn-light dropdown-toggle  w-100" }%>
      <br>
      <%= f.submit "Update", class: 'btn btn-success  my-2 w-100' %>
  <% end %>
</div>

app/views/fishings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fishings</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Text</th>
      <th>Imagen</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fishings.each do |fishing| %>
      <tr>
        <td><%= fishing.author_id %></td>
        <td><%= fishing.title %></td>
        <td><%= fishing.text %></td>
        <td><%= fishing.imagen %></td>
        <td><%= link_to 'Show', fishing %></td>
        <td><%= link_to 'Edit', edit_fishing_path(fishing) %></td>
        <td><%= link_to 'Destroy', fishing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fishing', new_fishing_path %>

app/views/fishings/new.html.erb
<div class="w-50 border border-secondary p-3 rounded centered_XY">
 
 <%fishing_errors%>
  <% @fishing.errors.full_messages.each do |msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  
  <h5 class="text-center titles_color">New Article</h5>
  <%= form_for @fishing, url: {action: "create"} do |f| %>
      <%= f.text_field :title, placeholder: "Title", class:"form-control my-2 #{@fclass1}" %>
      <%= f.text_field :text, placeholder: "Content", class:"form-control my-2 #{@fclass2}" %>
      <%= f.file_field :image, class:'form-control my-2' %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: 'Select a Category'}, { multiple: true, class: "btn btn-light dropdown-toggle  w-100" }%>
      <br>
      <%= f.submit "Create", class: 'btn btn-success  my-2 w-100' %>
  <% end %>
</div>

app/views/fishings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @fishing.author_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @fishing.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @fishing.text %>
</p>

<p>
  <strong>Imagen:</strong>
  <%= @fishing.imagen %>
</p>

<%= link_to 'Edit', edit_fishing_path(@fishing) %> |
<%= link_to 'Back', fishings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/d6bf1861cd.js" crossorigin="anonymous"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>FishingArticlesCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="top-menu navbar border border-secondary fixed-top bg-white p-2">
      <%nav_bar_buttons%>

      <div class="d-flex align-content-center justify-content-center">
        <h2 class="titles_color">Fishing</h2>
        
      </div>

      <div>
        <p class="text-center"><%=@welcome%></p>
        <span class="px-2 titles_color"><%= link_to 'HOME', root_path, class: 'text-decoration-none'%></span>
        <%@categories = Category.all%>
        <%@categories.each do |c|%>
          <span class="px-2 titles_color"><%= link_to c.name, category_path(c), class: 'text-decoration-none'%></span>
        <%end %>
      </div>

      <div>
        <%= @su_button %>
        <%=@article%>
        <span>|</span>
        <%= @si_button %>
        <%= @so_button %>
        <i class="fas fa-search px-2 titles_color"></i>
      </div>
    </nav>
    <%= yield %>
    <footer class="bottom-menu navbar fixed-bottom p-2">
      <h2 class="text-white">Fishing</h2>
      <span class="text-white">Copyright 2021. All rights reserved</span>
      <div class="d-flex align-items-center">
        <span class="px-3 text-white">Connect wit us:</span>
        <i class="fab fa-twitter"></i>
        <i class="fab fa-instagram mx-3"></i>
        <i class="fab fa-facebook-f"></i>
      </div>
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="w-50 border border-secondary p-3 rounded centered_XY">
<%user_errors%>
<% @user.errors.full_messages.each do |msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
  <h5 class="text-center titles_color">Register</h5>
  <%= form_for @user, url: {action: "create"} do |f| %>
    <%= f.text_field :name, placeholder: "User name", class:"form-control #{@uclas1}"%><br />
    <%= f.submit "Create", class: 'btn btn-success w-100' %>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
        <% vote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user %>
  </div>

  <div class="field">
    <%= form.label :fishing_id %>
    <%= form.text_field :fishing_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Fishing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user %></td>
        <td><%= vote.fishing_id %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user %>
</p>

<p>
  <strong>Fishing:</strong>
  <%= @vote.fishing_id %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>